### ISSUE TITLE
Formating issue when rule's points is Null

### ISSUE THREAD

**Issue by HugoDelval** [Teamwork/go-spamc#21]
The condition here https://github.com/Teamwork/spamc/blob/master/spamc.go#L357 is wrong I think. When the points == 0 we want the extra space. I think the correct way to do it would be something like this https://github.com/Teamwork/spamc/pull/17/files#diff-8d2ae85476cf566f10f5851dc05ba527R359

**Comment by arp242** [comment]
Thanks! Rather than converting it to a string I fixed it by checking if the left-most bit is set, which indicates the floating point's sign. Should be a little bit faster :-)
